# config for MZT intron quantification snakemake pipeline #


# directory with fastqs and generated data
DATA: 
    "../data"

# directory for output databases
DBASES: 
    "../dbases" 

# genome fasta file
GENOMES:
    drosophila: "../dbases/drosophila/ext/Drosophila_melanogaster.BDGP6.dna.toplevel.fa"

# transcript annotation in GTF format
TRANSCRIPTS:
    drosophila: "../dbases/drosophila/ext/Drosophila_melanogaster.BDGP6.84.gtf"

# intron annotation in SAF format (see results/00.Rmd to generate from
# STAR alignments)
# leave blank if traditional alignmnet approach not needed
INTRONS:
    drosophila: "../dbases/drosophila/saf/fly_introns.saf"

EXONS:
    drosophila: "../dbases/drosophila/saf/fly_exons.saf"

# fasta index file
CHROM_SIZES:
    drosophila: "../dbases/drosophila/ext/Drosophila_melanogaster.BDGP6.dna.toplevel.fa.fai"

# Path to star index
GENOME_DIRS:
    drosophila: "../dbases/drosophila/star/BDGP6"

# experiment specific settings
# trim: settings for cutadapt
# intron/exon_count: settings for featureCounts, only run if introns/exons
# defined above
# stranded: either forward of reverse
# map: additional settings for salmon quantification
# bt_map: additional settings for bowtie2 mapping  
# fq: suffix for R1 and R2
#
RISSLAND:
    trim: " -q 10 -a 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC' "
    intron_count: " --minOverlap 10 -s 2 "
    exon_count: " --fracOverlap 1 -s 2 "
    map: " --fldMean 200 --fldSD 20 --libType 'SR' "
    stranded: "reverse"
    bt_map: " --nofw "
    fq: 
        - ".fastq.gz"

# sample names that indicate samples from the earliest timepoint in the timecourse
# (e.g. a zygote or other pre-ZGA sample). 
T0_SAMPLES:
    - "SRR5469986"
    - "SRR5469998"

# Path to file with library definitions
LIB_PARAMS: "fly_rissland_lib_params.tsv"

# directory for auxillary scripts
SRC: 
  "../src" 

# directory for R scripts
RSRC:
  "../R"
